---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/{{carrier_dir_name}}"
  - "{{ deploy_dir }}/{{carrier_dir_name}}/config"
  - "{{ deploy_dir }}/{{carrier_dir_name}}/log"
  - "{{ deploy_dir }}/{{carrier_dir_name}}/cert"
  - "{{ deploy_dir }}/{{carrier_dir_name}}/p2p_priv_key"
  - "{{ deploy_dir }}/{{carrier_dir_name}}/datadir"

- name: "copy carrier mirror tar file"
  copy:
    src: "{{ downloads_dir }}/{{ item.service }}.tar"
    dest: "{{ deploy_dir }}/{{carrier_dir_name}}/{{ item.service }}.tar"
  with_items: "{{ carrier_image }}"

# 加载镜像tar压缩包 
- name: Load carrier image from archive
  become: True
  become_method: sudo
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    # push: yes
    load_path: "{{ deploy_dir }}/{{carrier_dir_name}}/{{ item.service }}.tar"
    timeout: "{{docker_timeout|int}}"
    # source: load
    # force: yes
  with_items: "{{ carrier_image }}"

- name: "copy certificates"
  copy:
    src: "{{ carrier_cert_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/{{carrier_dir_name}}/cert/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - server.pem 
    - server.key

# Set the container internal path mapped to the host 
- name: set carrier_data_dir facts
  set_fact:
    carrier_data_dir: "{{ carrier_docker_path }}/datadir"

- name: Set certificate-related facts
  set_fact:
    carrier_tls_cert: "{{ carrier_docker_path }}/cert/server.pem"
    carrier_tls_key: "{{ carrier_docker_path }}/cert/server.key"

- name: set carrier_p2p_private_key facts
  set_fact:
    carrier_p2p_private_key: "{{ carrier_docker_path }}/p2p_priv_key/p2p_priv_key"

- name: "copy script"
  copy:
    src: "{{ script_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/{{carrier_dir_name}}/{{ item }}"
    mode: 0755
  with_items:
    - stop_container.sh
    - clean_docker.sh

- name: "Generate carrier.yml configuration file based on carrier.yml.j2 template file"
  template:
    src: "carrier.yml.j2"
    dest: "{{ deploy_dir }}/{{carrier_dir_name}}/config/carrier.yml"
    mode: 0600
    backup: yes

- name: "Generate docker-compose.yml configuration file based on docker-compose.yml.j2 template file"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ deploy_dir }}/{{carrier_dir_name}}/config/docker-compose.yml"
    mode: 0600
    backup: yes
