# via 服务配置模板
tls:
  #tls mode options: one_way, two_way
  mode: one_way

  viaCertFile: cert/server.crt
  viaKeyFile: cert/server.key

  ioCertFile: cert/client.crt
  ioKeyFile: cert/client.key

  caCertFile: cert/ca.crt
